# Generated by Django 2.0 on 2018-03-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='Überschrift')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('start_tp', models.DateTimeField(verbose_name='Start Zeitpunkt')),
                ('end_tp', models.DateTimeField(verbose_name='End Zeitpunkt')),
                ('short_desc', models.TextField(verbose_name='Beschreibung')),
                ('content', models.TextField(verbose_name='Inhalt')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(default='Gewerbeimmobilie', max_length=100, verbose_name='Kategorie')),
                ('short_desc', models.TextField(verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('info_overview', models.TextField(verbose_name='Info Übersicht')),
                ('images_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='none', max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pludg.Object')),
            ],
        ),
    ]
