# Generated by Django 2.0 on 2018-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pludg', '0002_auto_20180314_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'News Artikel', 'verbose_name_plural': 'News Artikel'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Objekt', 'verbose_name_plural': 'Objekte'},
        ),
        migrations.AlterModelOptions(
            name='objectimage',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AddField(
            model_name='object',
            name='location',
            field=models.CharField(default='Germany', max_length=100, verbose_name='Ort'),
        ),
    ]
